version: "2"
services:
  rmlmapper:
    container_name: rmlmapper
    image: rmlmapper:latest
    shm_size: '50gb'
    volumes:
      - ../data:/data
      - ../results/rmlmapper:/results
      - ../mappings:/mappings
      - ./rmlmapper:/rmlmapper
  rocketrml:
    container_name: rocketrml
    image: rocketrml:latest
    shm_size: '50gb'
    volumes:
      - ../data:/data
      - ../results/rocketrml:/results
      - ../mappings:/mappings
      - ./rocketrml:/rocketrml
  sdmrdfizer:
    container_name: sdmrdfizer
    image: sdmrdfizer:latest
    shm_size: '50gb'
    volumes:
      - ../data:/data
      - ../results/sdmrdfizer:/results
      - ../mappings:/mappings
      - ./sdmrdfizer:/sdmrdfizer
  funmap:
    container_name: funmap
    image: funmap:latest
    shm_size: '50gb'
    volumes:
      - ../data:/data
      - ../results/funmap:/results
      - ../mappings:/mappings
      - ./funmap:/funmap